ProjeCV/Controllers/KonferansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjeCV.Models.Entity;
using ProjeCV.Models.Sinif;
namespace ProjeCV.Controllers
{
    public class KonferansController : Controller
    {
        // GET: Konferans
        DbCvEntities db = new DbCvEntities();
        [Authorize(Users = "veysel.dogan@ogr.sakarya.edu.tr")]
        public ActionResult Index(string p)
        {
            var degerler = from d in db.TBLAWARDS select d;
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.AWARD.Contains(p));
            }
           // Class1 cs = new Class1();
           // cs.Deger6 = db.TBLAWARDS.ToList();
            return View(degerler.ToList());
        }
        [HttpGet]
        public ActionResult YeniKonferans()
        {
            return View();
        }



        [HttpPost]
        public ActionResult YeniKonferans(TBLAWARDS p)
        {
            db.TBLAWARDS.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KonferansSil(int id)
        {
            var konferans = db.TBLAWARDS.Find(id);
            db.TBLAWARDS.Remove(konferans);
            db.SaveChanges();
            return RedirectToAction("Index");
        }




        public ActionResult KonferansGetir(int id)
        {
            var konferans = db.TBLAWARDS.Find(id);
            return View("KonferansGetir", konferans);
        }
        public ActionResult Guncelle(TBLAWARDS p)
        {
            var veriler = db.TBLAWARDS.Find(p.ID);
            veriler.AWARD = p.AWARD;
            db.SaveChanges();
            return RedirectToAction("Index");
        }



    }
}

ProjeCV/Views/Konferans/Index.cshtml
@using ProjeCV.Models.Entity
@model List<TBLAWARDS>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Index", "Konferans", FormMethod.Get))
{
    <p>
        @Html.TextBox("p")
        <input type="submit" value="Ara"/>
    </p>
}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>KONFERANSLAR</th>
            <th>Sil</th>
            <th>Güncelle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
        <tr>
            <th>@x.ID</th>
            <td>@x.AWARD</td>
            <td>@Html.ActionLink("Sil", "KonferansSil", new { id = x.ID }, new { @class = "btn btn-warning", onclick = "return confirm('Silmek istiyor musunuz?')" })</td>
            <td><a href="/Konferans/KonferansGetir/@x.ID" class="btn btn-success">Güncelle</a></td>
        </tr>
            }
    </tbody>
</table>
<a href="/Konferans/YeniKonferans" class="btn btn-info">Yeni Konferans Ekle</a>

ProjeCV/Views/Konferans/KonferansGetir.cshtml
@model ProjeCV.Models.Entity.TBLAWARDS

@{
    ViewBag.Title = "KonferansGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Konferans", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.ID)
        @Html.TextBoxFor(m => m.ID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.AWARD)
        @Html.TextBoxFor(m => m.AWARD, new { @class = "form-control" })
        <br />
        <button class="btn btn-primary">Güncelle</button>
    </div>
}

ProjeCV/Views/Konferans/YeniKonferans.cshtml
@{
    ViewBag.Title = "YeniKonferans";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">
    <div>
        <label>Konferans</label>
        <input type="text" class="form-control" name="AWARD" />
    </div>

    <br />
    <button class="btn btn-primary">Kaydet</button>

</form>