ProjeCV/Controllers/DeneyimlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjeCV.Models.Entity;
using ProjeCV.Models.Sinif;
namespace ProjeCV.Controllers
{
    public class DeneyimlerController : Controller
    {
        // GET: Deneyimler
        DbCvEntities db = new DbCvEntities();
        [Authorize(Users = "veysel.dogan@ogr.sakarya.edu.tr")]
        public ActionResult Index()
        {
            Class1 cs = new Class1();
            cs.Deger2 = db.TBLEXPERIENCE.ToList();
            return View(cs);
        }
        [HttpGet]
        public ActionResult YeniDeneyim()
        {
            return View();
        }



        [HttpPost]
        public ActionResult YeniDeneyim(TBLEXPERIENCE p)
        {
            db.TBLEXPERIENCE.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeneyimSil(int id)
        {
            var deneyim = db.TBLEXPERIENCE.Find(id);
            db.TBLEXPERIENCE.Remove(deneyim);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeneyimGetir(int id)
        {
            var veri = db.TBLEXPERIENCE.Find(id);
            return View("DeneyimGetir", veri);
        }
        public ActionResult Guncelle(TBLEXPERIENCE p)
        {
            var veriler = db.TBLEXPERIENCE.Find(p.ID);
            veriler.TITLE = p.TITLE;
            veriler.SUBTITLE = p.SUBTITLE;
            veriler.DETAILS = p.DETAILS;
            veriler.DATE = p.DATE;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ProjeCV/Views/Deneyimler/DeneyimGetir.cshtml
@model ProjeCV.Models.Entity.TBLEXPERIENCE
@{
    ViewBag.Title = "DeneyimGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


@using (Html.BeginForm("Guncelle", "Deneyimler", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.ID)
        @Html.TextBoxFor(m => m.ID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.TITLE)
        @Html.TextBoxFor(m => m.TITLE, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.SUBTITLE)
        @Html.TextBoxFor(m => m.SUBTITLE, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.DATE)
        @Html.TextBoxFor(m => m.DATE, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.DETAILS)
        @Html.TextAreaFor(m => m.DETAILS, new { @class = "form-control" })
        <br />
        <button class="btn btn-primary">Güncelle</button>
    </div>
}

ProjeCV/Views/Deneyimler/Index.cshtml
@model  ProjeCV.Models.Sinif.Class1
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>BAŞLIK</th>
            <th>ALTBAŞLIK</th>
            <th>TARİH</th>
            <th>DETAYLAR</th>
            <th>Sil</th>
            <th>Güncelle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model.Deger2)
        {
        <tr>
            <th>@x.ID</th>
            <td>@x.TITLE</td>
            <td>@x.SUBTITLE</td>
            <td>@x.DATE</td>
            <td>@x.DETAILS</td>
            <td>@Html.ActionLink("Sil", "DeneyimSil", new { id = x.ID }, new { @class = "btn btn-warning", onclick = "return confirm('Silmek istiyor musunuz?')" })</td>
            <td><a href="/Deneyimler/DeneyimGetir/@x.ID" class="btn btn-success">Güncelle</a></td>
        </tr>
        }
    </tbody>
</table>


<a href="/Deneyimler/YeniDeneyim/" class="btn btn-info">Yeni Deneyim Ekle</a>

ProjeCV/Views/Deneyimler/YeniDeneyim.cshtml
@{
    ViewBag.Title = "YeniDeneyim";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

    <form class="form-group" method="post">
        <div>
            <label>Deneyim Başlığı</label>
            <input type="text" class="form-control" name="TITLE" />
        </div>

        <br />

        <div>
            <label>Deneyim Alt Başlığı</label>
            <input type="text" class="form-control" name="SUBTITLE" />
        </div>

        <br />

        <div>
            <label>Tarih</label>
            <input type="text" class="form-control" name="DATE" />
        </div>

        <br />

        <div>
            <label>Detaylar</label>
            <textarea class="form-control" rows="10" name="DETAILS"></textarea>
        </div>

        <br />

        <button class="btn btn-primary">Kaydet</button>

    </form>