ProjeCV/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjeCV.Models.Entity;
using ProjeCV.Models.Sinif;
namespace ProjeCV.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        DbCvEntities db = new DbCvEntities();
        [Authorize]
        public ActionResult Index()
        {
            Class1 cs = new Class1();
            cs.Deger1 = db.TBLABOUT.ToList();
            cs.Deger2 = db.TBLEXPERIENCE.ToList();
            cs.Deger3 = db.TBLEDUCATION.ToList();
            cs.Deger4 = db.TBLSKILLS.ToList();
            cs.Deger5 = db.TBLINTEREST.ToList();
            cs.Deger6 = db.TBLAWARDS.ToList();

            return View(cs);

            //var degerler = db.TBLABOUT.ToList();
            //return View(degerler);
        }
    }
}

ProjeCV/Controllers/HakkimdaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjeCV.Models.Entity;
using ProjeCV.Models.Sinif;
namespace ProjeCV.Controllers
{
    public class HakkimdaController : Controller
    {
        // GET: Hakkimda
        DbCvEntities db = new DbCvEntities();
        [Authorize(Users = "veysel.dogan@ogr.sakarya.edu.tr")]
        public ActionResult Index()
        {
            Class1 cs = new Class1();
            cs.Deger1 = db.TBLABOUT.ToList();
            return View(cs);
        }
        public ActionResult VeriGetir(int id)
        {
            var veriler = db.TBLABOUT.Find(id);
            return View("VeriGetir", veriler);
        }
        public ActionResult Guncelle (TBLABOUT p)
        {
            var degerler = db.TBLABOUT.Find(p.ID);
            degerler.NAME = p.NAME;
            degerler.SURNAME = p.SURNAME;
            degerler.PHONE = p.PHONE;
            degerler.MAIL = p.MAIL;
            degerler.ABOUT = p.ABOUT;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ProjeCV/Controllers/HobilerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjeCV.Models.Entity;
using ProjeCV.Models.Sinif;
using PagedList;
using PagedList.Mvc;
namespace ProjeCV.Controllers
{
    public class HobilerController : Controller
    {
        // GET: Hobiler
        DbCvEntities db = new DbCvEntities();
        [Authorize(Users = "veysel.dogan@ogr.sakarya.edu.tr")]
        public ActionResult Index(int sayfa=1)
        {
           var degerler = db.TBLINTEREST.ToList().ToPagedList(sayfa,5);
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniHobi()
        {
            return View();
        }



        [HttpPost]
        public ActionResult YeniHobi(TBLINTEREST p)
        {
            db.TBLINTEREST.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult HobiSil(int id)
        {
            var hobi = db.TBLINTEREST.Find(id);
            db.TBLINTEREST.Remove(hobi);
            db.SaveChanges();
            return RedirectToAction("Index");
        }




        public ActionResult HobiGetir(int id)
        {
            var hobi = db.TBLINTEREST.Find(id);
            return View("HobiGetir", hobi);
        }
        public ActionResult Guncelle(TBLINTEREST p)
        {
            var veriler = db.TBLINTEREST.Find(p.ID);
            veriler.INTEREST = p.INTEREST;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}
  

ProjeCV/Controllers/YetenekController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjeCV.Models.Entity;
using ProjeCV.Models.Sinif;
using PagedList;
using PagedList.Mvc;
namespace ProjeCV.Controllers
{
    public class YetenekController : Controller
    {
        // GET: Yetenek
        DbCvEntities db = new DbCvEntities();
        [Authorize(Users = "veysel.dogan@ogr.sakarya.edu.tr")]
        public ActionResult Index(int sayfa=1)
        {
           // Class1 cs = new Class1();
            var degerler = db.TBLSKILLS.ToList().ToPagedList(sayfa, 8);
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniYetenek()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniYetenek(TBLSKILLS p)
        {
            db.TBLSKILLS.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult YetenekSil(int id)
        {
            var yetenek = db.TBLSKILLS.Find(id);
            db.TBLSKILLS.Remove(yetenek);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult YetenekGetir(int id)
        {
            var yetenek = db.TBLSKILLS.Find(id);
            return View("YetenekGetir", yetenek);
        }
        public ActionResult Guncelle(TBLSKILLS p)
        {
            var veriler = db.TBLSKILLS.Find(p.ID);
            veriler.SKILL = p.SKILL;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ProjeCV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET Uygulamam</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Veysel|2019", "Index", "Default", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr /
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ProjeCV/Views/Shared/_MainLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/Default/Index">Veysel|2019</a>
            </div>
            <ul class="nav navbar-nav">
             
                <li>@Html.ActionLink(ProjeCV.Resources.ProjeCVHomeTexts.hakkimda,"Index","Hakkimda")</li>
                <li>@Html.ActionLink(ProjeCV.Resources.ProjeCVHomeTexts.deneyimlerim, "Index", "Deneyimler")</li>
                <li>@Html.ActionLink(ProjeCV.Resources.ProjeCVHomeTexts.egitim, "Index", "Egitim")</li>
                <li>@Html.ActionLink(ProjeCV.Resources.ProjeCVHomeTexts.yeteneklerim, "Index", "Yetenek")</li>
                <li>@Html.ActionLink(ProjeCV.Resources.ProjeCVHomeTexts.hobilerim, "Index", "Hobiler")</li>
                <li>@Html.ActionLink(ProjeCV.Resources.ProjeCVHomeTexts.konferanslarim, "Index", "Konferans")</li>
                <li>@Html.ActionLink(ProjeCV.Resources.ProjeCVHomeTexts.dil, "Index", "Language")</li>
                <li>@DateTime.Now.ToString()</li>
                @Html.Partial("_LoginPartial")

            </ul>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>

</body>
</html>